services:
  server:
    build: .
    container_name: project-node
    ports:
      - "9000:9000"
    environment:
      - PORT=9000
    working_dir: /src
    command: sh -c "npm install && npm run dev"
    volumes:
      - .:/src
      - /src/node_modules
    networks:
      - tj-net

networks:
  tj-net:
    name: tj-net
